# Generated by Django 6.0 on 2025-12-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('superadmin', 'SuperAdmin')], default='customer', max_length=20),
        ),
    ]
